# Generated by Django 3.1 on 2020-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterpage', '0002_auto_20200904_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='bg',
            field=models.CharField(default='n/a', max_length=20, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.CharField(default='n/a', max_length=20, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='creator',
            field=models.CharField(default='n/a', max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='feats_traits',
            field=models.TextField(default='Features, traits', verbose_name='features and traits'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='profs_lang',
            field=models.TextField(default='Proficiencies, languages', verbose_name='proficiencies and languages'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='spell_abl',
            field=models.CharField(default='n/a', max_length=10, verbose_name='spellcasting ability'),
        ),
    ]
