# Generated by Django 3.1 on 2020-09-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterpage', '0003_auto_20200904_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackspell',
            name='damage',
            field=models.CharField(default='n/a', max_length=20, verbose_name='damage/type'),
        ),
        migrations.AlterField(
            model_name='attackspell',
            name='name',
            field=models.CharField(default='n/a', max_length=30, verbose_name='attack name'),
        ),
        migrations.AlterField(
            model_name='charspells',
            name='name',
            field=models.CharField(default='n/a', max_length=30, verbose_name='Spell Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='n/a', max_length=50, verbose_name='equipment'),
        ),
    ]
